// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneMoneyCloneServer.Persistence;

#nullable disable

namespace OneMoneyCloneServer.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Budgets", (string)null);
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.CategoryTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryTags", (string)null);
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Decimals")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7f7d728-50bb-6ab4-f38d-9d150256df4e"),
                            Code = "AED",
                            Decimals = 2,
                            Name = "United Arab Emirates Dirham",
                            Symbol = "د.إ."
                        },
                        new
                        {
                            Id = new Guid("23a6f372-126a-5fb7-033d-9a2529a3b875"),
                            Code = "AFN",
                            Decimals = 2,
                            Name = "Afghan Afghani",
                            Symbol = "Af"
                        },
                        new
                        {
                            Id = new Guid("55f9b15f-5eb4-e338-1789-286a1790398d"),
                            Code = "ALL",
                            Decimals = 2,
                            Name = "Albanian Lek",
                            Symbol = "L"
                        },
                        new
                        {
                            Id = new Guid("4143af48-45f7-3f16-945f-a838eeabb062"),
                            Code = "AMD",
                            Decimals = 2,
                            Name = "Armenian Dram",
                            Symbol = "֏"
                        },
                        new
                        {
                            Id = new Guid("264a68ea-3fe2-4a56-fb94-93fad725556e"),
                            Code = "ANG",
                            Decimals = 2,
                            Name = "Netherlands Antillean Guilder",
                            Symbol = "ƒ"
                        },
                        new
                        {
                            Id = new Guid("af34431f-41e8-f7c3-6efb-f4f5504e9a0a"),
                            Code = "AOA",
                            Decimals = 2,
                            Name = "Angolan Kwanza",
                            Symbol = "Kz"
                        },
                        new
                        {
                            Id = new Guid("f667c2a3-5fac-b765-19c6-c65eb6d1c5a6"),
                            Code = "ARS",
                            Decimals = 2,
                            Name = "Argentine Peso",
                            Symbol = "AR$"
                        },
                        new
                        {
                            Id = new Guid("497cabbf-8f99-6358-fb8d-10c7f0ed8873"),
                            Code = "AUD",
                            Decimals = 2,
                            Name = "Australian Dollar",
                            Symbol = "AU$"
                        },
                        new
                        {
                            Id = new Guid("f36e5a06-b4d8-3dcf-1bde-04d9705bebcc"),
                            Code = "AWG",
                            Decimals = 2,
                            Name = "Aruban Florin",
                            Symbol = "ƒ"
                        },
                        new
                        {
                            Id = new Guid("20758c97-14c5-0a1a-f188-f86e764e90da"),
                            Code = "AZN",
                            Decimals = 2,
                            Name = "Azerbaijani Manat",
                            Symbol = "ман"
                        },
                        new
                        {
                            Id = new Guid("7f8a7b1a-7e17-4e02-1685-e780c47649c6"),
                            Code = "BAM",
                            Decimals = 2,
                            Name = "Bosnia and Herzegovina Convertible Mark",
                            Symbol = "KM"
                        },
                        new
                        {
                            Id = new Guid("991de080-b526-e74f-2941-0d78954faada"),
                            Code = "BBD",
                            Decimals = 2,
                            Name = "Barbadian Dollar",
                            Symbol = "BBD$"
                        },
                        new
                        {
                            Id = new Guid("e59274d8-5375-83dd-4ebe-968ab2cc8107"),
                            Code = "BDT",
                            Decimals = 2,
                            Name = "Bangladeshi Taka",
                            Symbol = "৳"
                        },
                        new
                        {
                            Id = new Guid("865e727c-1a56-f1f1-b941-5bf0ea0679c9"),
                            Code = "BGN",
                            Decimals = 2,
                            Name = "Bulgarian Lev",
                            Symbol = "лв."
                        },
                        new
                        {
                            Id = new Guid("fca255c7-60b6-4f09-0d71-2c90fcd40753"),
                            Code = "BHD",
                            Decimals = 3,
                            Name = "Bahraini Dinar",
                            Symbol = "BD"
                        },
                        new
                        {
                            Id = new Guid("bb3eb81a-8de5-8518-632b-175f762eb77a"),
                            Code = "BIF",
                            Decimals = 2,
                            Name = "Burundian Franc",
                            Symbol = "FBu"
                        },
                        new
                        {
                            Id = new Guid("e504b448-b390-35e4-ec21-9a6f1cec68b4"),
                            Code = "BMD",
                            Decimals = 2,
                            Name = "Bermudian Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("b11bc376-a47a-c585-8620-656a77c13b11"),
                            Code = "BND",
                            Decimals = 2,
                            Name = "Brunei Dollar",
                            Symbol = "B$"
                        },
                        new
                        {
                            Id = new Guid("cf385935-b7e3-623a-4297-591972d27c01"),
                            Code = "BOB",
                            Decimals = 2,
                            Name = "Bolivian Boliviano",
                            Symbol = "Bs."
                        },
                        new
                        {
                            Id = new Guid("a34a0b1a-bb61-1553-e304-831a320f89b3"),
                            Code = "BRL",
                            Decimals = 2,
                            Name = "Brazilian Real",
                            Symbol = "R$"
                        },
                        new
                        {
                            Id = new Guid("3be039c5-b2e7-c869-a84f-85437bc8d298"),
                            Code = "BSD",
                            Decimals = 2,
                            Name = "Bahamian Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("9c6da159-d466-bf88-850d-7fb1e36c4e38"),
                            Code = "BTN",
                            Decimals = 2,
                            Name = "Bhutanese Ngultrum",
                            Symbol = "Nu."
                        },
                        new
                        {
                            Id = new Guid("3fcdf238-6be6-8a7b-64b4-6bc06880d4b7"),
                            Code = "BWP",
                            Decimals = 2,
                            Name = "Botswana Pula",
                            Symbol = "P"
                        },
                        new
                        {
                            Id = new Guid("d12a4f79-1e8c-bbd9-c158-1fe4589fba1b"),
                            Code = "BYN",
                            Decimals = 2,
                            Name = "Belarusian Ruble",
                            Symbol = "Br"
                        },
                        new
                        {
                            Id = new Guid("678cf412-186c-e9ce-f424-d11554c49415"),
                            Code = "BZD",
                            Decimals = 2,
                            Name = "Belize Dollar",
                            Symbol = "BZ$"
                        },
                        new
                        {
                            Id = new Guid("5409cbec-a9fc-00f2-5aea-084605df5ee9"),
                            Code = "CAD",
                            Decimals = 2,
                            Name = "Canadian Dollar",
                            Symbol = "CA$"
                        },
                        new
                        {
                            Id = new Guid("d3c63cb7-d3c1-f4fb-c49a-ea0b307498dd"),
                            Code = "CDF",
                            Decimals = 2,
                            Name = "Congolese Franc",
                            Symbol = "FC"
                        },
                        new
                        {
                            Id = new Guid("2e05c22f-45aa-9a73-9fd0-854d4ed60178"),
                            Code = "CHF",
                            Decimals = 2,
                            Name = "Swiss Franc",
                            Symbol = "Fr."
                        },
                        new
                        {
                            Id = new Guid("7d2c2e91-b5f8-e9d7-63a9-cd82bf0f612f"),
                            Code = "CKD",
                            Decimals = 2,
                            Name = "Cook Islands Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("fa0c8d5a-d7ad-d6ef-c44c-000085157da7"),
                            Code = "CLP",
                            Decimals = 0,
                            Name = "Chilean Peso",
                            Symbol = "CL$"
                        },
                        new
                        {
                            Id = new Guid("33e99e88-891f-9214-f89b-1e578fa377e0"),
                            Code = "CNY",
                            Decimals = 2,
                            Name = "Chinese Yuan",
                            Symbol = "CN¥"
                        },
                        new
                        {
                            Id = new Guid("c1c5af97-029a-4c01-fde1-c064281437c5"),
                            Code = "COP",
                            Decimals = 2,
                            Name = "Colombian Peso",
                            Symbol = "CO$"
                        },
                        new
                        {
                            Id = new Guid("845d4b1a-32a0-4a8c-33bd-669c608a34c3"),
                            Code = "CRC",
                            Decimals = 2,
                            Name = "Costa Rican Colon",
                            Symbol = "₡"
                        },
                        new
                        {
                            Id = new Guid("3bad9f41-82f0-1748-27a2-d47adce883a8"),
                            Code = "CUC",
                            Decimals = 2,
                            Name = "Cuban convertible Peso",
                            Symbol = "CUC$"
                        },
                        new
                        {
                            Id = new Guid("2d96115b-e8cb-e55d-5770-d22d3e5fb85a"),
                            Code = "CUP",
                            Decimals = 2,
                            Name = "Cuban Peso",
                            Symbol = "$MN"
                        },
                        new
                        {
                            Id = new Guid("df7be16e-7d4a-06a2-068f-e02847a4aed5"),
                            Code = "CVE",
                            Decimals = 2,
                            Name = "Cabo Verdean Escudo",
                            Symbol = "CV$"
                        },
                        new
                        {
                            Id = new Guid("508e79f7-53e5-34b2-27e7-df0a7a2652f5"),
                            Code = "CZK",
                            Decimals = 2,
                            Name = "Czech Koruna",
                            Symbol = "Kč"
                        },
                        new
                        {
                            Id = new Guid("457a12d5-3622-804c-5de5-104bb5503310"),
                            Code = "DJF",
                            Decimals = 2,
                            Name = "Djiboutian Franc",
                            Symbol = "Fdj"
                        },
                        new
                        {
                            Id = new Guid("4164005b-94e6-45cb-a1af-078e58a66a87"),
                            Code = "DKK",
                            Decimals = 2,
                            Name = "Danish Krone",
                            Symbol = "kr."
                        },
                        new
                        {
                            Id = new Guid("559286f0-9158-16e1-1c5a-ef5b2748d7cb"),
                            Code = "DOP",
                            Decimals = 2,
                            Name = "Dominican Peso",
                            Symbol = "RD$"
                        },
                        new
                        {
                            Id = new Guid("a83f0076-dba8-821c-36e0-ce931221b956"),
                            Code = "DZD",
                            Decimals = 2,
                            Name = "Algerian Dinar",
                            Symbol = "DA"
                        },
                        new
                        {
                            Id = new Guid("ff1bede6-ec71-2ab0-bbf8-7ff7e45ea08d"),
                            Code = "EGP",
                            Decimals = 2,
                            Name = "Egyptian Pound",
                            Symbol = "E£"
                        },
                        new
                        {
                            Id = new Guid("c38bddf4-a29d-6b76-7408-d47a540aae25"),
                            Code = "EHP",
                            Decimals = 2,
                            Name = "Sahrawi Peseta",
                            Symbol = "Ptas."
                        },
                        new
                        {
                            Id = new Guid("b356e5fe-69d1-2ebd-a6fb-e8e71f0ade0a"),
                            Code = "ERN",
                            Decimals = 2,
                            Name = "Eritrean Nakfa",
                            Symbol = "Nkf"
                        },
                        new
                        {
                            Id = new Guid("38a3c1b4-829b-a079-ee13-5fb1f8368255"),
                            Code = "ETB",
                            Decimals = 2,
                            Name = "Ethiopian Birr",
                            Symbol = "Br"
                        },
                        new
                        {
                            Id = new Guid("2b5655a0-59db-8bad-a9cc-680367308118"),
                            Code = "EUR",
                            Decimals = 2,
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            Id = new Guid("68f951a8-ddb8-06a6-535c-03efee304638"),
                            Code = "FJD",
                            Decimals = 2,
                            Name = "Fijian Dollar",
                            Symbol = "FJ$"
                        },
                        new
                        {
                            Id = new Guid("9ec98535-c765-76fb-b3a0-76723dc90c5f"),
                            Code = "FKP",
                            Decimals = 2,
                            Name = "Falkland Islands Pound",
                            Symbol = "FK£"
                        },
                        new
                        {
                            Id = new Guid("d6d95096-73d6-1255-28bb-1042f482459f"),
                            Code = "FOK",
                            Decimals = 2,
                            Name = "Faroese Króna",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = new Guid("8522dd3a-4f09-31dc-8690-2810080c1465"),
                            Code = "GBP",
                            Decimals = 2,
                            Name = "Pound Sterling",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = new Guid("19c11074-e05c-e42f-5957-2628e9510004"),
                            Code = "GEL",
                            Decimals = 2,
                            Name = "Georgian Lari",
                            Symbol = "₾"
                        },
                        new
                        {
                            Id = new Guid("0c2207d4-a840-043c-a181-13629f23a763"),
                            Code = "GGP",
                            Decimals = 2,
                            Name = "Guernsey Pound",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = new Guid("2428a728-cc03-1770-c9e1-d5d3f5041bfd"),
                            Code = "GHS",
                            Decimals = 2,
                            Name = "Ghanaian Cedi",
                            Symbol = "GH₵"
                        },
                        new
                        {
                            Id = new Guid("0a4231a1-7e53-1a6d-2523-079b0e28f991"),
                            Code = "GIP",
                            Decimals = 2,
                            Name = "Gibraltar Pound",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = new Guid("2b0ea592-0b3e-5ba4-28ab-150a385bafcc"),
                            Code = "GMD",
                            Decimals = 2,
                            Name = "Gambian Dalasi",
                            Symbol = "D"
                        },
                        new
                        {
                            Id = new Guid("926eca77-9f15-2b68-db43-52af6058eb92"),
                            Code = "GNF",
                            Decimals = 2,
                            Name = "Guinean Franc",
                            Symbol = "FG"
                        },
                        new
                        {
                            Id = new Guid("67614275-c295-93eb-6397-1960a03be6d0"),
                            Code = "GTQ",
                            Decimals = 2,
                            Name = "Guatemalan Quetzal",
                            Symbol = "Q"
                        },
                        new
                        {
                            Id = new Guid("e185868b-8361-d093-0e8a-87328b75ddd6"),
                            Code = "GYD",
                            Decimals = 2,
                            Name = "Guyanese Dollar",
                            Symbol = "G$"
                        },
                        new
                        {
                            Id = new Guid("2a050d05-a326-9d10-0fb0-6176ee1db8e8"),
                            Code = "HKD",
                            Decimals = 2,
                            Name = "Hong Kong Dollar",
                            Symbol = "HK$"
                        },
                        new
                        {
                            Id = new Guid("7441bca5-d568-c3c8-7867-2f6bdd2e0c90"),
                            Code = "HNL",
                            Decimals = 2,
                            Name = "Honduran Lempira",
                            Symbol = "L"
                        },
                        new
                        {
                            Id = new Guid("bb221ac1-7c55-feae-8a0f-3535dbf6d201"),
                            Code = "HRK",
                            Decimals = 2,
                            Name = "Croatian Kuna",
                            Symbol = "kn"
                        },
                        new
                        {
                            Id = new Guid("40554325-f171-792b-a96a-c865112a53e0"),
                            Code = "HTG",
                            Decimals = 2,
                            Name = "Haitian Gourde",
                            Symbol = "G"
                        },
                        new
                        {
                            Id = new Guid("60c073b8-2a92-f667-4ac0-9d27d1232f3a"),
                            Code = "HUF",
                            Decimals = 2,
                            Name = "Hungarian Forint",
                            Symbol = "Ft"
                        },
                        new
                        {
                            Id = new Guid("1b522f66-c212-d240-c3c1-95f3df817b0c"),
                            Code = "IDR",
                            Decimals = 2,
                            Name = "Indonesian Rupiah",
                            Symbol = "Rp"
                        },
                        new
                        {
                            Id = new Guid("7eaaeee8-73e1-02b2-12e4-0babe414c5c0"),
                            Code = "ILS",
                            Decimals = 2,
                            Name = "Israeli new Shekel",
                            Symbol = "₪"
                        },
                        new
                        {
                            Id = new Guid("9cc1be6e-a3f0-09a6-354a-05acde9ca8af"),
                            Code = "IMP",
                            Decimals = 2,
                            Name = "Manx Pound",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = new Guid("c8e8fa4f-bdc3-24a7-e6cc-853513870137"),
                            Code = "INR",
                            Decimals = 2,
                            Name = "Indian Rupee",
                            Symbol = "Rs."
                        },
                        new
                        {
                            Id = new Guid("74b8c512-dd0b-9dc2-a376-7cf7aa684995"),
                            Code = "IQD",
                            Decimals = 3,
                            Name = "Iraqi Dinar",
                            Symbol = "د.ع."
                        },
                        new
                        {
                            Id = new Guid("cf6aa1ea-10a1-b24c-23a5-5fb03fdde12f"),
                            Code = "IRR",
                            Decimals = 2,
                            Name = "Iranian Rial",
                            Symbol = "﷼"
                        },
                        new
                        {
                            Id = new Guid("b1507d3f-5e68-147b-f5bf-abf8b30c703a"),
                            Code = "ISK",
                            Decimals = 2,
                            Name = "Icelandic Krona",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = new Guid("ae5c7dce-0da4-e7f9-59a2-c1e0ec747f69"),
                            Code = "JEP",
                            Decimals = 2,
                            Name = "Jersey Pound",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = new Guid("5e7281f1-c8b3-2546-bc1c-77fa4b39f47c"),
                            Code = "JMD",
                            Decimals = 2,
                            Name = "Jamaican Dollar",
                            Symbol = "J$"
                        },
                        new
                        {
                            Id = new Guid("1bd8d6bb-55fc-36c3-03ed-6378bc630669"),
                            Code = "JOD",
                            Decimals = 3,
                            Name = "Jordanian Dinar",
                            Symbol = "JD"
                        },
                        new
                        {
                            Id = new Guid("5d29220d-29ba-8a8b-4831-a943545b0810"),
                            Code = "JPY",
                            Decimals = 2,
                            Name = "Japanese Yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = new Guid("4fde0da3-c7fc-d1ac-174a-05337056b552"),
                            Code = "KES",
                            Decimals = 2,
                            Name = "Kenyan Shilling",
                            Symbol = "KSh"
                        },
                        new
                        {
                            Id = new Guid("48c67697-6737-dacd-e0a3-8b6149c08539"),
                            Code = "KGS",
                            Decimals = 2,
                            Name = "Kyrgyzstani Som",
                            Symbol = "с"
                        },
                        new
                        {
                            Id = new Guid("d261eb65-f310-f4ec-45f5-12103e765526"),
                            Code = "KHR",
                            Decimals = 2,
                            Name = "Cambodian Riel",
                            Symbol = "៛"
                        },
                        new
                        {
                            Id = new Guid("5a6da5a4-7482-44d7-b1ab-9678d60901bf"),
                            Code = "KID",
                            Decimals = 2,
                            Name = "Kiribati Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("e87ef008-3803-cfd2-4fd6-5e7bc1909085"),
                            Code = "KMF",
                            Decimals = 2,
                            Name = "Comorian Franc",
                            Symbol = "CF"
                        },
                        new
                        {
                            Id = new Guid("d0b6ec83-0781-82a9-b9f7-495d3c265446"),
                            Code = "KPW",
                            Decimals = 2,
                            Name = "North Korean Won",
                            Symbol = "₩"
                        },
                        new
                        {
                            Id = new Guid("a0093fc2-1d1b-f9d2-4308-1b0b6febaf99"),
                            Code = "KRW",
                            Decimals = 2,
                            Name = "South Korean Won",
                            Symbol = "₩"
                        },
                        new
                        {
                            Id = new Guid("297a1d27-54c7-bdea-6a11-0781a1adbd2d"),
                            Code = "KWD",
                            Decimals = 3,
                            Name = "Kuwaiti Dinar",
                            Symbol = "KD"
                        },
                        new
                        {
                            Id = new Guid("a47b9428-0b75-c0ac-947b-e464145e08b0"),
                            Code = "KYD",
                            Decimals = 2,
                            Name = "Cayman Islands Dollar",
                            Symbol = "CI$"
                        },
                        new
                        {
                            Id = new Guid("6cb14b53-b3e9-e872-099d-b6081da2f962"),
                            Code = "KZT",
                            Decimals = 2,
                            Name = "Kazakhstani Tenge",
                            Symbol = "₸"
                        },
                        new
                        {
                            Id = new Guid("2a574ebe-f04e-cd45-c914-49b6c9435a8a"),
                            Code = "LAK",
                            Decimals = 2,
                            Name = "Lao Kip",
                            Symbol = "₭N"
                        },
                        new
                        {
                            Id = new Guid("ee86f9f3-a4ad-f71a-77ef-5911d96c51ac"),
                            Code = "LBP",
                            Decimals = 2,
                            Name = "Lebanese Pound",
                            Symbol = "LL."
                        },
                        new
                        {
                            Id = new Guid("47321ae7-6977-c8ba-d129-a02cd467e3e6"),
                            Code = "LKR",
                            Decimals = 2,
                            Name = "Sri Lankan Rupee",
                            Symbol = "Rs."
                        },
                        new
                        {
                            Id = new Guid("e5bf28d5-c9f0-ba92-ffcc-8a7bef5cdcfb"),
                            Code = "LRD",
                            Decimals = 2,
                            Name = "Liberian Dollar",
                            Symbol = "L$"
                        },
                        new
                        {
                            Id = new Guid("eab80530-6fb9-df81-142d-787d501d0537"),
                            Code = "LSL",
                            Decimals = 2,
                            Name = "Lesotho Loti",
                            Symbol = "L"
                        },
                        new
                        {
                            Id = new Guid("76e21711-52fc-c8e1-2ab6-7059d9ceca48"),
                            Code = "LYD",
                            Decimals = 3,
                            Name = "Libyan Dinar",
                            Symbol = "LD"
                        },
                        new
                        {
                            Id = new Guid("820e7293-9d3d-f29a-3230-95152cb82906"),
                            Code = "MAD",
                            Decimals = 2,
                            Name = "Moroccan Dirham",
                            Symbol = "DH"
                        },
                        new
                        {
                            Id = new Guid("a8318d34-a02f-20f4-fc0c-de4a1d0d845d"),
                            Code = "MDL",
                            Decimals = 2,
                            Name = "Moldovan Leu",
                            Symbol = "L"
                        },
                        new
                        {
                            Id = new Guid("f293e3e4-f89a-c8aa-d614-354c3d5f3f4b"),
                            Code = "MGA",
                            Decimals = 0,
                            Name = "Malagasy Ariary",
                            Symbol = "Ar"
                        },
                        new
                        {
                            Id = new Guid("02a94805-cd8a-6362-c147-e79e4f88cba9"),
                            Code = "MKD",
                            Decimals = 2,
                            Name = "Macedonian Denar",
                            Symbol = "den"
                        },
                        new
                        {
                            Id = new Guid("44c6af00-1d9b-9ff3-464e-a2ca3e56af77"),
                            Code = "MMK",
                            Decimals = 2,
                            Name = "Myanmar Kyat",
                            Symbol = "Ks"
                        },
                        new
                        {
                            Id = new Guid("4227f44f-52f9-693e-8b35-154f999f49a2"),
                            Code = "MNT",
                            Decimals = 2,
                            Name = "Mongolian Tögrög",
                            Symbol = "₮"
                        },
                        new
                        {
                            Id = new Guid("401229af-21e2-0ebb-94c2-f09ee87606cf"),
                            Code = "MOP",
                            Decimals = 2,
                            Name = "Macanese Pataca",
                            Symbol = "MOP$"
                        },
                        new
                        {
                            Id = new Guid("9954e1d1-d339-c1bd-caa1-0f65876dba6c"),
                            Code = "MRU",
                            Decimals = 0,
                            Name = "Mauritanian Ouguiya",
                            Symbol = "UM"
                        },
                        new
                        {
                            Id = new Guid("9f39b2f0-bfd4-d113-d6a8-e7bf52b27483"),
                            Code = "MUR",
                            Decimals = 2,
                            Name = "Mauritian Rupee",
                            Symbol = "Rs."
                        },
                        new
                        {
                            Id = new Guid("5010968a-0037-6def-0d6c-1caf8f04ed9f"),
                            Code = "MVR",
                            Decimals = 2,
                            Name = "Maldivian Rufiyaa",
                            Symbol = "MRf"
                        },
                        new
                        {
                            Id = new Guid("86a6cb2d-72bf-6816-8c21-aaf78f409d11"),
                            Code = "MWK",
                            Decimals = 2,
                            Name = "Malawian Kwacha",
                            Symbol = "MK"
                        },
                        new
                        {
                            Id = new Guid("c04f60fd-b0da-9def-793c-9598ae881435"),
                            Code = "MXN",
                            Decimals = 2,
                            Name = "Mexican Peso",
                            Symbol = "MX$"
                        },
                        new
                        {
                            Id = new Guid("8f676eb4-47c5-c84e-216c-5e3f4e9d327c"),
                            Code = "MYR",
                            Decimals = 2,
                            Name = "Malaysian Ringgit",
                            Symbol = "RM"
                        },
                        new
                        {
                            Id = new Guid("9cd2c5bf-a278-f366-3479-d3fbad222d43"),
                            Code = "MZN",
                            Decimals = 2,
                            Name = "Mozambican Metical",
                            Symbol = "MTn"
                        },
                        new
                        {
                            Id = new Guid("5b568650-0456-1b07-2d45-d42afcb0d3e9"),
                            Code = "NAD",
                            Decimals = 2,
                            Name = "Namibian Dollar",
                            Symbol = "N$"
                        },
                        new
                        {
                            Id = new Guid("98884324-53da-bf34-fffc-8ac71ad2bb4e"),
                            Code = "NGN",
                            Decimals = 2,
                            Name = "Nigerian Naira",
                            Symbol = "₦"
                        },
                        new
                        {
                            Id = new Guid("c0dfd9b6-54fb-7327-21ce-bc0fff55df2f"),
                            Code = "NIO",
                            Decimals = 2,
                            Name = "Nicaraguan Córdoba",
                            Symbol = "C$"
                        },
                        new
                        {
                            Id = new Guid("22d1a99d-f0fd-1d1b-b281-6592e00f28ad"),
                            Code = "NOK",
                            Decimals = 2,
                            Name = "Norwegian Krone",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = new Guid("1d521a8c-1e10-4db2-139d-c9ddfa30002f"),
                            Code = "NPR",
                            Decimals = 2,
                            Name = "Nepalese Rupee",
                            Symbol = "Rs."
                        },
                        new
                        {
                            Id = new Guid("4e913f2e-5a32-a01c-cb82-a132af1002d3"),
                            Code = "NZD",
                            Decimals = 2,
                            Name = "New Zealand Dollar",
                            Symbol = "NZ$"
                        },
                        new
                        {
                            Id = new Guid("d41f5c78-f550-26b4-27e7-9c1890076425"),
                            Code = "OMR",
                            Decimals = 3,
                            Name = "Omani Rial",
                            Symbol = "OR"
                        },
                        new
                        {
                            Id = new Guid("8375f4dc-9f02-d679-4904-cf78daa360cb"),
                            Code = "PAB",
                            Decimals = 2,
                            Name = "Panamanian Balboa",
                            Symbol = "B/."
                        },
                        new
                        {
                            Id = new Guid("a41afad3-9f5b-6ee5-1fc1-b558d8ed6678"),
                            Code = "PEN",
                            Decimals = 2,
                            Name = "Peruvian Sol",
                            Symbol = "S/."
                        },
                        new
                        {
                            Id = new Guid("15656902-67e6-5096-baae-b843d97cafd7"),
                            Code = "PGK",
                            Decimals = 2,
                            Name = "Papua New Guinean Kina",
                            Symbol = "K"
                        },
                        new
                        {
                            Id = new Guid("2339ec2f-a504-3ac2-c138-da22847f9b7c"),
                            Code = "PHP",
                            Decimals = 2,
                            Name = "Philippine Peso",
                            Symbol = "₱"
                        },
                        new
                        {
                            Id = new Guid("cbb16792-48c6-0e0d-a037-217688b3a655"),
                            Code = "PKR",
                            Decimals = 2,
                            Name = "Pakistani Rupee",
                            Symbol = "Rs."
                        },
                        new
                        {
                            Id = new Guid("ea876644-b12d-a7ad-5be5-ed053be77f59"),
                            Code = "PLN",
                            Decimals = 2,
                            Name = "Polish Zloty",
                            Symbol = "zł"
                        },
                        new
                        {
                            Id = new Guid("d0319b6f-b5ec-f704-dcc8-690d7c7840e1"),
                            Code = "PND",
                            Decimals = 2,
                            Name = "Pitcairn Islands Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("3e768d90-f1cf-0469-58ba-5863ae3b894f"),
                            Code = "PRB",
                            Decimals = 2,
                            Name = "Transnistrian Ruble",
                            Symbol = "р."
                        },
                        new
                        {
                            Id = new Guid("d8eed51b-a077-453f-eeb9-e0d518e4834a"),
                            Code = "PYG",
                            Decimals = 2,
                            Name = "Paraguayan Guaraní",
                            Symbol = "₲"
                        },
                        new
                        {
                            Id = new Guid("bf3ae3b9-0846-74c4-1652-596350ea9718"),
                            Code = "QAR",
                            Decimals = 2,
                            Name = "Qatari Riyal",
                            Symbol = "QR"
                        },
                        new
                        {
                            Id = new Guid("285dfed9-f150-16ed-7451-b193e8bd0e0c"),
                            Code = "RON",
                            Decimals = 2,
                            Name = "Romanian Leu",
                            Symbol = "L"
                        },
                        new
                        {
                            Id = new Guid("9ce1bd44-0ebc-0b83-caf0-54b5413dd39d"),
                            Code = "RSD",
                            Decimals = 2,
                            Name = "Serbian Dinar",
                            Symbol = "din"
                        },
                        new
                        {
                            Id = new Guid("43476567-32cc-eedf-bf2d-2d154db69cd8"),
                            Code = "RUB",
                            Decimals = 2,
                            Name = "Russian Ruble",
                            Symbol = "₽"
                        },
                        new
                        {
                            Id = new Guid("eb4e9cc2-372e-d597-e676-21f51f3aecc1"),
                            Code = "RWF",
                            Decimals = 2,
                            Name = "Rwandan Franc",
                            Symbol = "FRw"
                        },
                        new
                        {
                            Id = new Guid("1fdc9b26-aab1-c5dc-b575-a68220158602"),
                            Code = "SAR",
                            Decimals = 2,
                            Name = "Saudi Riyal",
                            Symbol = "SR"
                        },
                        new
                        {
                            Id = new Guid("7e312460-dd5b-62df-aa29-5395cbde54ab"),
                            Code = "SBD",
                            Decimals = 2,
                            Name = "Solomon Islands Dollar",
                            Symbol = "SI$"
                        },
                        new
                        {
                            Id = new Guid("d59cc2b9-3cf8-5b53-0bca-f31343315bad"),
                            Code = "SCR",
                            Decimals = 2,
                            Name = "Seychellois Rupee",
                            Symbol = "Rs."
                        },
                        new
                        {
                            Id = new Guid("744e6169-b041-9b1c-a6d4-974080d6d099"),
                            Code = "SDG",
                            Decimals = 2,
                            Name = "Sudanese Pound",
                            Symbol = "£SD"
                        },
                        new
                        {
                            Id = new Guid("4e6b6ab8-67b2-a95a-8b7a-63b568434502"),
                            Code = "SEK",
                            Decimals = 2,
                            Name = "Swedish Krona",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = new Guid("5ff7ec50-7710-d2e1-50a7-81764b89cbc2"),
                            Code = "SGD",
                            Decimals = 2,
                            Name = "Singapore Dollar",
                            Symbol = "S$"
                        },
                        new
                        {
                            Id = new Guid("a10a44f7-44ba-740f-555d-4c313c9b7677"),
                            Code = "SHP",
                            Decimals = 2,
                            Name = "Saint Helena Pound",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = new Guid("bdcf2eae-d495-dd75-f088-76080d57e3d9"),
                            Code = "SLL",
                            Decimals = 2,
                            Name = "Sierra Leonean Leone",
                            Symbol = "Le"
                        },
                        new
                        {
                            Id = new Guid("50c1f0d5-899f-17ff-8497-1832af4e7670"),
                            Code = "SLS",
                            Decimals = 2,
                            Name = "Somaliland Shilling",
                            Symbol = "Sl"
                        },
                        new
                        {
                            Id = new Guid("ede1d560-b630-558d-e6a1-8004b2d17ad2"),
                            Code = "SOS",
                            Decimals = 2,
                            Name = "Somali Shilling",
                            Symbol = "Sh.So."
                        },
                        new
                        {
                            Id = new Guid("ed4e06a4-e091-a871-d451-e0d09b480f78"),
                            Code = "SRD",
                            Decimals = 2,
                            Name = "Surinamese Dollar",
                            Symbol = "Sr$"
                        },
                        new
                        {
                            Id = new Guid("55dcd9ca-ba10-12f0-abf9-02dfa6bd3ad0"),
                            Code = "SSP",
                            Decimals = 2,
                            Name = "South Sudanese Pound",
                            Symbol = "SS£"
                        },
                        new
                        {
                            Id = new Guid("6988531f-2c0f-c510-a68a-c0b28696fd8b"),
                            Code = "STN",
                            Decimals = 2,
                            Name = "Sao Tome and Príncipe Dobra",
                            Symbol = "Db"
                        },
                        new
                        {
                            Id = new Guid("ac3f818d-37c4-8127-2b29-79fc265e4cad"),
                            Code = "SVC",
                            Decimals = 2,
                            Name = "Salvadoran Colón",
                            Symbol = "₡"
                        },
                        new
                        {
                            Id = new Guid("0dd3fce2-1222-e0e6-a029-704038803f37"),
                            Code = "SYP",
                            Decimals = 2,
                            Name = "Syrian Pound",
                            Symbol = "LS"
                        },
                        new
                        {
                            Id = new Guid("e3366b73-b522-3659-97b4-927d6d9132ab"),
                            Code = "SZL",
                            Decimals = 2,
                            Name = "Swazi Lilangeni",
                            Symbol = "L"
                        },
                        new
                        {
                            Id = new Guid("b9f73528-6807-e1ac-225a-7821f5bcd131"),
                            Code = "THB",
                            Decimals = 2,
                            Name = "Thai Baht",
                            Symbol = "฿"
                        },
                        new
                        {
                            Id = new Guid("b439a2fe-d174-b9a0-0401-6873d4f1ee24"),
                            Code = "TJS",
                            Decimals = 2,
                            Name = "Tajikistani Somoni",
                            Symbol = "SM"
                        },
                        new
                        {
                            Id = new Guid("362ac415-3d05-4f89-ef1a-225ce99a3a2b"),
                            Code = "TMT",
                            Decimals = 2,
                            Name = "Turkmenistan Manat",
                            Symbol = "m."
                        },
                        new
                        {
                            Id = new Guid("6a767c32-79c8-096b-f63d-a407c9c8967b"),
                            Code = "TND",
                            Decimals = 3,
                            Name = "Tunisian Dinar",
                            Symbol = "DT"
                        },
                        new
                        {
                            Id = new Guid("7b770567-2e71-11e8-e76f-b07162081d63"),
                            Code = "TOP",
                            Decimals = 2,
                            Name = "Tongan Paʻanga",
                            Symbol = "T$"
                        },
                        new
                        {
                            Id = new Guid("3fb8df59-ac7c-3c4e-8ee9-1700ef2ad90d"),
                            Code = "TRY",
                            Decimals = 2,
                            Name = "Turkish Lira",
                            Symbol = "TL"
                        },
                        new
                        {
                            Id = new Guid("0d956a48-d79a-dea3-d9f6-fe8a13803a97"),
                            Code = "TTD",
                            Decimals = 2,
                            Name = "Trinidad and Tobago Dollar",
                            Symbol = "TT$"
                        },
                        new
                        {
                            Id = new Guid("a97206d9-bbf4-6a2b-a4dc-96ed2b419af0"),
                            Code = "TVD",
                            Decimals = 2,
                            Name = "Tuvaluan Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("770c05bb-8592-2f63-0e53-2eab4d629b1c"),
                            Code = "TWD",
                            Decimals = 2,
                            Name = "New Taiwan Dollar",
                            Symbol = "NT$"
                        },
                        new
                        {
                            Id = new Guid("030483f1-a13c-1859-73b9-752835a31c07"),
                            Code = "TZS",
                            Decimals = 2,
                            Name = "Tanzanian Shilling",
                            Symbol = "TSh"
                        },
                        new
                        {
                            Id = new Guid("39bdf548-263b-b98c-f43a-86af1a4d9e8c"),
                            Code = "UAH",
                            Decimals = 2,
                            Name = "Ukrainian Hryvnia",
                            Symbol = "₴"
                        },
                        new
                        {
                            Id = new Guid("fdaa9392-8e6e-d492-bb85-e72de96fd369"),
                            Code = "UGX",
                            Decimals = 2,
                            Name = "Ugandan Shilling",
                            Symbol = "USh"
                        },
                        new
                        {
                            Id = new Guid("94f81835-424d-2d21-d37d-affe097d216e"),
                            Code = "USD",
                            Decimals = 2,
                            Name = "United States Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("1289187c-d210-cdae-27ae-a1e09562a989"),
                            Code = "UYU",
                            Decimals = 2,
                            Name = "Uruguayan Peso",
                            Symbol = "$U"
                        },
                        new
                        {
                            Id = new Guid("affb8a7b-6a90-9670-01db-6e066a527dd1"),
                            Code = "UZS",
                            Decimals = 2,
                            Name = "Uzbekistani Som",
                            Symbol = "сум"
                        },
                        new
                        {
                            Id = new Guid("6e156d15-a487-437a-5879-313a5ef39da4"),
                            Code = "VED",
                            Decimals = 2,
                            Name = "Venezuelan bolívar digital",
                            Symbol = "Bs."
                        },
                        new
                        {
                            Id = new Guid("a8afda91-e019-0ea0-fed5-b683ec81b9b2"),
                            Code = "VES",
                            Decimals = 2,
                            Name = "Venezuelan Bolívar Soberano",
                            Symbol = "Bs.F"
                        },
                        new
                        {
                            Id = new Guid("ce256ef1-ecc4-b3ca-e643-a66a8eccb1cb"),
                            Code = "VND",
                            Decimals = 2,
                            Name = "Vietnamese Dong",
                            Symbol = "₫"
                        },
                        new
                        {
                            Id = new Guid("5423cf5d-7420-563b-3642-2f69a2f7822c"),
                            Code = "VUV",
                            Decimals = 0,
                            Name = "Vanuatu Vatu",
                            Symbol = "VT"
                        },
                        new
                        {
                            Id = new Guid("53203a98-f729-bc7e-1712-be17806b8b0a"),
                            Code = "WST",
                            Decimals = 2,
                            Name = "Samoan Tala",
                            Symbol = "T"
                        },
                        new
                        {
                            Id = new Guid("9ecde9a9-ad81-da58-5b9a-608f70e1d7d9"),
                            Code = "XAF",
                            Decimals = 2,
                            Name = "Central African CFA Franc BEAC",
                            Symbol = "Fr"
                        },
                        new
                        {
                            Id = new Guid("cfda8d44-5193-1202-7e2c-6374c945725d"),
                            Code = "XCD",
                            Decimals = 2,
                            Name = "East Caribbean Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("fd4cad0d-8381-fc1c-78ca-2aca02283588"),
                            Code = "XOF",
                            Decimals = 2,
                            Name = "West African CFA Franc BCEAO",
                            Symbol = "₣"
                        },
                        new
                        {
                            Id = new Guid("1c7010ea-6905-a818-1dc8-9906b9019c35"),
                            Code = "XPF",
                            Decimals = 0,
                            Name = "CFP Franc (Franc Pacifique)",
                            Symbol = "₣"
                        },
                        new
                        {
                            Id = new Guid("36a1cc65-7ef9-f628-ea8c-af95ba0be3d6"),
                            Code = "YER",
                            Decimals = 2,
                            Name = "Yemeni Rial",
                            Symbol = "YR"
                        },
                        new
                        {
                            Id = new Guid("a03a80ff-17c5-da03-a2da-b2119613aa6f"),
                            Code = "ZAR",
                            Decimals = 2,
                            Name = "South African Rand",
                            Symbol = "R"
                        },
                        new
                        {
                            Id = new Guid("15127fd9-5505-772c-09f4-a998ebe7d84e"),
                            Code = "ZMW",
                            Decimals = 2,
                            Name = "Zambian Kwacha",
                            Symbol = "ZK"
                        },
                        new
                        {
                            Id = new Guid("a5da4d34-06e9-0e91-af8b-8df4656a8551"),
                            Code = "ZWB",
                            Decimals = 0,
                            Name = "RTGS Dollar",
                            Symbol = ""
                        },
                        new
                        {
                            Id = new Guid("6f821189-ba30-9c98-56aa-38112064db7d"),
                            Code = "ZWL",
                            Decimals = 2,
                            Name = "Zimbabwean Dollar",
                            Symbol = "Z$"
                        },
                        new
                        {
                            Id = new Guid("f0f39460-5873-4369-5cdb-49c60235bffe"),
                            Code = "Abkhazia",
                            Decimals = 0,
                            Name = "Abkhazian Apsar",
                            Symbol = ""
                        },
                        new
                        {
                            Id = new Guid("fb14d36d-e4ae-ce2a-0874-5f9bbaf3da54"),
                            Code = "Artsakh",
                            Decimals = 2,
                            Name = "Artsakh Dram",
                            Symbol = "դր."
                        });
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.SavingsBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AmountInMainCurrency")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("UserId");

                    b.ToTable("SavingsBudgets", (string)null);
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.TagBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("CategoryTagId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryTagId");

                    b.HasIndex("UserId");

                    b.ToTable("TagBudgets", (string)null);
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AmountInAccountCurrency")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AmountInMainCurrency")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryTagId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TransferAccountId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryTagId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("TransferAccountId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MainCurrencyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MainCurrencyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OneMoneyCloneServer.Models.Server.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OneMoneyCloneServer.Models.Server.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneMoneyCloneServer.Models.Server.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OneMoneyCloneServer.Models.Server.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.Account", b =>
                {
                    b.HasOne("OneMoneyCloneServer.Models.Server.Currency", "Currency")
                        .WithMany("Accounts")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneMoneyCloneServer.Models.Server.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.Budget", b =>
                {
                    b.HasOne("OneMoneyCloneServer.Models.Server.Category", "Category")
                        .WithMany("SavingsBudgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneMoneyCloneServer.Models.Server.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.Category", b =>
                {
                    b.HasOne("OneMoneyCloneServer.Models.Server.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.CategoryTag", b =>
                {
                    b.HasOne("OneMoneyCloneServer.Models.Server.Category", "Category")
                        .WithMany("CategoryTags")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.RefreshToken", b =>
                {
                    b.HasOne("OneMoneyCloneServer.Models.Server.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.SavingsBudget", b =>
                {
                    b.HasOne("OneMoneyCloneServer.Models.Server.Account", "Account")
                        .WithMany("SavingsBudgets")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneMoneyCloneServer.Models.Server.User", "User")
                        .WithMany("SavingBudgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.TagBudget", b =>
                {
                    b.HasOne("OneMoneyCloneServer.Models.Server.CategoryTag", "CategoryTag")
                        .WithMany("TagBudgets")
                        .HasForeignKey("CategoryTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneMoneyCloneServer.Models.Server.User", "User")
                        .WithMany("TagBudgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryTag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.Transaction", b =>
                {
                    b.HasOne("OneMoneyCloneServer.Models.Server.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneMoneyCloneServer.Models.Server.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId");

                    b.HasOne("OneMoneyCloneServer.Models.Server.CategoryTag", null)
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryTagId");

                    b.HasOne("OneMoneyCloneServer.Models.Server.Currency", "Currency")
                        .WithMany("Transactions")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneMoneyCloneServer.Models.Server.Account", "TransferAccount")
                        .WithMany()
                        .HasForeignKey("TransferAccountId");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Currency");

                    b.Navigation("TransferAccount");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.User", b =>
                {
                    b.HasOne("OneMoneyCloneServer.Models.Server.Currency", "MainCurrency")
                        .WithMany("Users")
                        .HasForeignKey("MainCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainCurrency");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.Account", b =>
                {
                    b.Navigation("SavingsBudgets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.Category", b =>
                {
                    b.Navigation("CategoryTags");

                    b.Navigation("SavingsBudgets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.CategoryTag", b =>
                {
                    b.Navigation("TagBudgets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.Currency", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Transactions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OneMoneyCloneServer.Models.Server.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Budgets");

                    b.Navigation("Categories");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SavingBudgets");

                    b.Navigation("TagBudgets");
                });
#pragma warning restore 612, 618
        }
    }
}
