name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Stop running containers
        run: docker-compose down || true

      - name: Build and Deploy Containers
        run: |
          docker-compose build
          docker-compose up -d
